meta_product_name: "Cap.cat"
meta_title: "Cap.cat - le site de l'artiste electro hiphop"
meta_description: "Retrouvez toutes les actualités de l'artiste cap.cat ainsi que tous ses projets : electro, hiphop, piano ..."
meta_image: "meta-img.jpg" # Une image dans votre dossier app/assets/images/